describe("User Authentication", () => {
  it("should require acceptance of terms before joining", () => {
    cy.visit("/join")
    cy.get('[data-testid="first-name"]', { timeout: 10000 }).as("firstName").should("be.visible")
    cy.get("@firstName").type("New")
    cy.get('[data-testid="last-name"]', { timeout: 10000 }).as("lastName").should("be.visible")
    cy.get("@lastName").type("User")
    cy.get('[data-testid="email"]', { timeout: 10000 }).as("email").should("be.visible")
    cy.get("@email").type("newuser@example.com")
    cy.get('[data-testid="password"]', { timeout: 10000 }).as("password").should("be.visible")
    cy.get("@password").type("password123@A")
    cy.get('[data-testid="confirm-password"]', { timeout: 10000 })
      .as("confirmPassword")
      .should("be.visible")
    cy.get("@confirmPassword").type("password123@A")
    cy.wait(500)
    cy.get('input[type="checkbox"]', { timeout: 10000 }).check()
    cy.get('button[type="submit"]', { timeout: 10000 }).as("joinButton").click()
    cy.get("@joinButton").click()
    cy.url().should("not.include", "/join")
    cy.contains("Welcome").should("be.visible")
  })
})
